Second challenge of Css challenges with image
susird/css_challenges pull request #2
Opened 2021-04-08 17:02 UTC by susird

This is the pr of second challenge :sparkles:

2021-04-23 23:55 UTC, josepplloo requested changes
Use margin to avoid repeating yourself in margin-right margin-left and in general we try tu use position relative in the container and absolute in the elements inside the container

2021-04-25 19:27 UTC, anyruizd commented on challenge_2/index.html
> +</html>
Remember to add a blank line at the end of the file.
```suggestion
</html>

```

2021-04-25 19:28 UTC, anyruizd commented on challenge_2/style.css
> +}
Same here
```suggestion
}

```

2021-04-25 19:28 UTC, anyruizd commented on challenge_2/style.css
> +  border-radius: 100%;
It's not necessary to put 100%, if you want to accomplish a full circle, with `border-radius: 50%` would be enough 😉

2021-04-26 21:36 UTC, josepplloo requested changes
Why `.container` have position absolute?

2021-04-26 22:27 UTC, josepplloo requested changes

2021-04-26 22:27 UTC, josepplloo commented on challenge_2/index.html
> +
fix those spaces

2021-04-27 10:54 UTC, josepplloo approved these changes
lgtm 🚀

2021-04-27 14:40 UTC, anyruizd commented on challenge_2/style.css
> +  border-radius: 100%;
😆

2021-04-27 14:41 UTC, anyruizd approved these changes
just one small comment

2021-04-29 21:49 UTC, merged