3th challenge of css challenges
susird/css_challenges pull request #3
Opened 2021-04-09 21:48 UTC by susird

This is the pr for 3th css challenge :dizzy:

2021-04-15 18:44 UTC, anyruizd commented on challenge_3/style.css
> +  margin-top: 150px;
Remember: `margin: top right bottom left` as in a clock🕐 . Change these to be only one: 
```suggestion
  margin: 150px 0 0 50px;
```

2021-04-16 02:50 UTC, anyruizd requested changes

2021-04-16 02:50 UTC, anyruizd commented on challenge_3/style.css
> +  border-bottom-right-radius: 3em 3em;
Convert this to pixels.

2021-04-16 02:50 UTC, anyruizd commented on challenge_3/style.css
> +  border-top-right-radius: 3em 3em;
same here

2021-04-16 02:50 UTC, anyruizd commented on challenge_3/style.css
> +  margin-top: 45px;
same here

2021-04-16 02:50 UTC, anyruizd commented on challenge_3/style.css
> +  border-bottom-right-radius: 3em 3em;
same here

2021-04-16 02:50 UTC, anyruizd commented on challenge_3/style.css
> +  background: #62306D;
Let's use css custom properties (variables) for the colors.  See this example of its usage https://developer.mozilla.org/en-US/docs/Web/CSS/--*#css

2021-04-16 02:50 UTC, anyruizd commented on challenge_3/index.html
> +</html>
Needs an ending blank line.

2021-04-16 02:50 UTC, anyruizd commented on challenge_3/style.css
> +}
blank line

2021-04-16 03:03 UTC, anyruizd requested changes
These requested changes apply for everything you do from now on.

2021-04-24 01:13 UTC, josepplloo reviewed
Lgtm

2021-04-24 01:13 UTC, josepplloo commented on challenge_3/style.css
> +  border-bottom-right-radius: 48px 48px;
You could use border radius to avoid use border radius right /left

2021-04-26 21:37 UTC, josepplloo commented on challenge_3/style.css
> +  --first-color: #F7EC7D;
nice

2021-04-26 21:39 UTC, josepplloo requested changes

2021-04-26 21:39 UTC, josepplloo commented on challenge_3/style.css
> +  height: 300px;
order alphabetically

2021-04-29 21:56 UTC, josepplloo approved these changes
nice werk 😂

2021-04-29 21:57 UTC, josepplloo commented on challenge_3/style.css
> +}
new line at the end

2021-04-30 19:14 UTC, anyruizd commented on challenge_3/style.css
> +  background: #62306D;
You're still missing this color as a css variable.

2021-04-30 20:24 UTC, anyruizd approved these changes

2021-04-30 20:25 UTC, merged