Challenge 4 "Eye of the Tiger"
susird/css_challenges pull request #4
Opened 2021-04-26 23:46 UTC by susird

This is the pr for the challenge "Eye of the Tiger"  :sparkle: 
![image](https://user-images.githubusercontent.com/42523734/116164525-782b4c80-a6bf-11eb-8f9b-179c1fe3da3f.png)

2021-04-27 14:42 UTC, anyruizd commented
you forgot to .gitignore the node_modules folder 
![image](https://user-images.githubusercontent.com/29681222/116261014-d9453580-a73c-11eb-9e27-94e7a500d5b4.png)

2021-04-27 14:43 UTC, anyruizd requested changes
please remove the node_modules folder

2021-04-27 20:00 UTC, anyruizd requested changes

2021-04-27 20:00 UTC, anyruizd commented on README.md
> +![image](img_challenge4.png)
Nice! 😄

2021-04-27 20:00 UTC, anyruizd commented on challenge_4/.gitignore
> +.vscode/
❤️

2021-04-27 20:00 UTC, anyruizd commented on challenge_4/css/main.css
> +  height: 140px; }
This file shouldn't be uploaded 😄 please add it to the gitignore as well.

2021-04-27 20:00 UTC, anyruizd commented on challenge_4/sass/main.scss
> +$secondary-color: #0B2429;
Amazing 👍🏽

2021-04-27 20:00 UTC, anyruizd commented on challenge_4/sass/main.scss
> +}
Both of these triangles share most of the properties, so you are repeating styles with the same values. To avoid this, you could add a class to both triangles called `triangle`, then inside that class goes all the styles shared between them and in the `.right-triangle` and `.left-triangle` classes the specific style for each triangle. And also, since you're now using sass, you can use the nesting superpower and it should be something like this: 

```suggestion
.triangle {
  // common styles for both triangles
  
  &-right {
    // styles for the right triangle
  }
  
  &-left {
    // styles for the left triangle
  }
}
```
Keep in mind that if you want to nest the styles like this, the classes for the triangles should be named `triangle-right` and `triangle-left`.

2021-04-27 20:00 UTC, anyruizd commented on challenge_4/sass/main.scss
> +}
End line!

2021-04-27 20:00 UTC, anyruizd commented on challenge_4/sass/main.scss
> +    border-right: 48px solid #998235;
Use color variables here please.

2021-04-27 20:00 UTC, anyruizd commented on challenge_4/sass/main.scss
> +  height: 140px;
- [ ] You can also nest these circles: 

```css
.circle {
  &-big {...}
  &-middle {...}
  &-smallest {...}
}
```

- [ ] And please use variables for the colors

2021-04-30 13:42 UTC, josepplloo requested changes

2021-04-30 13:42 UTC, josepplloo commented on challenge_4/.gitignore
> +*.css.map
ignore also `css /main.css` path because is the output file, the important one is the sass file

2021-04-30 13:42 UTC, josepplloo commented on challenge_4/sass/main.scss
> + &-big {
ident this section

2021-04-30 13:42 UTC, josepplloo commented on challenge_4/index.html
> +    <div class="circle"></div>
the common way to do this exercise is using position relative in the parent container https://css-tricks.com/the-shapes-of-css/

2021-04-30 20:41 UTC, susird commented on challenge_4/.gitignore
> +*.css.map
solved line 4

2021-04-30 21:47 UTC, susird commented on challenge_4/index.html
> +    <div class="circle"></div>
dda6612

2021-04-30 23:40 UTC, josepplloo reviewed
nice! just a reminder: delete main.css and add a blank line at EOF in main.scss

2021-05-02 22:10 UTC, anyruizd approved these changes

2021-05-02 22:12 UTC, josepplloo approved these changes
💅 nice!

2021-05-02 22:12 UTC, merged